name: Cypress Web Tests
on:
  push:
    branches:
      - main
      - teste_pipeline
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Generate HTML report
      - run: node generate-html-report.js

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/report
